/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.3/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application

    id("org.openjfx.javafxplugin") version "0.0.8"
    id("org.beryx.jlink") version "2.25.0"
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    implementation(group = "org.apache.commons", name = "commons-lang3", version = "3.1")
    implementation(group = "org.apache.commons", name = "commons-csv", version = "1.7")
    implementation(group = "net.java.dev.jna", name = "jna", version = "4.5.0")
    implementation(group = "org.seleniumhq.selenium", name = "selenium-chrome-driver", version = "3.141.59")
    implementation(group = "org.jsoup", name = "jsoup", version = "1.12.1")


    // Use JUnit test framework
    testImplementation("junit:junit:4.13.2")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

application {
    // Define the main class for the application
    mainClassName = "com.danielpclin/com.danielpclin.spotifyLyrics.App"
}

javafx {
    modules("javafx.controls", "javafx.fxml")
}

tasks.withType<JavaCompile>{
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>{
    options.encoding = "UTF-8"
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = application.mainClassName
    }

    from(configurations.runtime.get().map {if (it.isDirectory) it else zipTree(it)})
}

jlink{
    mergedModule {
        requires("jdk.crypto.ec")
    }

    launcher {
        name = "Spotify Lyrics"
        noConsole = true
    }
    imageZip.set(project.file("$buildDir/distributions/${rootProject.name}-${javafx.platform.classifier}.zip"))
}